export const categories = [
  { id: "all", label: "Todos", icon: "Grid3X3" },
  { id: "nature", label: "Natureza", icon: "Trees" },
  { id: "abstract", label: "Abstrato", icon: "Sparkles" },
  { id: "space", label: "Espaço", icon: "Rocket" },
  { id: "city", label: "Cidade", icon: "Building2" },
  { id: "minimal", label: "Minimalista", icon: "Circle" },
  { id: "ocean", label: "Oceano", icon: "Waves" },
  { id: "mountains", label: "Montanhas", icon: "Mountain" },
  { id: "dark", label: "Dark", icon: "Moon" },
  { id: "animals", label: "Animais", icon: "Cat" },
];

export const queryByCategory = {
  all: "vertical wallpaper",
  nature: "nature vertical wallpaper",
  space: "space vertical wallpaper",
  abstract: "abstract vertical wallpaper",
  city: "city night vertical wallpaper",
  minimal: "minimal vertical wallpaper",
  ocean: "ocean vertical wallpaper",
  mountains: "mountain vertical wallpaper",
  dark: "dark aesthetic vertical wallpaper",
  animals: "wildlife vertical wallpaper",
};

const wallpaperSeed = [
  {
    id: "fallback_1",
    title: "Aurora Silenciosa",
    author: "Colecao local",
    category: "nature",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_2",
    title: "Nebulosa Neon",
    author: "Colecao local",
    category: "space",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_3",
    title: "Luz Urbana",
    author: "Colecao local",
    category: "city",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_4",
    title: "Ondas de Cor",
    author: "Colecao local",
    category: "abstract",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_5",
    title: "Minimal Duna",
    author: "Colecao local",
    category: "minimal",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_6",
    title: "Mar de Cobalto",
    author: "Colecao local",
    category: "ocean",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_7",
    title: "Serra Nebulosa",
    author: "Colecao local",
    category: "mountains",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_8",
    title: "Noite Violeta",
    author: "Colecao local",
    category: "dark",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_9",
    title: "Guardiao Selvagem",
    author: "Colecao local",
    category: "animals",
    source: "Fallback",
    url: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1080&q=80",
    thumb: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
];

export const wallpapers = wallpaperSeed.map((item) => ({
  ...item,
  imageUrl: item.url,
  thumbnailUrl: item.thumb,
}));

export const fallbackWallpapers = wallpapers.map((item) => ({
  ...item,
  imageUrl: item.imageUrl,
  thumbnailUrl: item.thumbnailUrl,
}));
