export const categories = [
  { id: "all", label: "Todos" },
  { id: "nature", label: "Natureza" },
  { id: "space", label: "Espaco" },
  { id: "abstract", label: "Abstrato" },
  { id: "city", label: "Cidade" },
  { id: "minimal", label: "Minimal" },
];

export const queryByCategory = {
  all: "vertical wallpaper",
  nature: "nature vertical wallpaper",
  space: "space vertical wallpaper",
  abstract: "abstract vertical wallpaper",
  city: "city night vertical wallpaper",
  minimal: "minimal vertical wallpaper",
};

export const fallbackWallpapers = [
  {
    id: "fallback_1",
    title: "Aurora Silenciosa",
    author: "Colecao local",
    category: "nature",
    source: "Fallback",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1080&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_2",
    title: "Nebulosa Neon",
    author: "Colecao local",
    category: "space",
    source: "Fallback",
    imageUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1080&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_3",
    title: "Luz Urbana",
    author: "Colecao local",
    category: "city",
    source: "Fallback",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1080&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_4",
    title: "Ondas de Cor",
    author: "Colecao local",
    category: "abstract",
    source: "Fallback",
    imageUrl: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?auto=format&fit=crop&w=1080&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
  {
    id: "fallback_5",
    title: "Minimal Duna",
    author: "Colecao local",
    category: "minimal",
    source: "Fallback",
    imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1080&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80",
    orientation: "portrait",
    license: "Preview",
  },
];
